apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "ingress-lb"
  namespace: "default"
spec:
  backend:
    serviceName: "reload-app-client"
    servicePort: 80
  rules:
  - http:
      paths:
      - path: "/api/*"
        backend:
          serviceName: "reload-app-server-service"
          servicePort: 3000